.test: &test
  label: "Test"
  command: "ci/run"
  env:
    SHARED_MASTER_CACHE: true
    DOCKER_IMAGE: gcr.io/opensourcecoin/radicle-registry-eth/ci-base:d78a964e22d65fe45e1dcacdf5538de286e3624e
    DOCKER_FILE: ci/base-image/Dockerfile
  agents:
    platform: "linux"
    production: "true"
  artifact_paths:
    - "radicle-contracts-*.tgz"

steps:
  - branches: master
    concurrency: 1
    concurrency_group: master
    <<: *test
  - branches: "!master"
    <<: *test

notify:
  - email: "registry-devs@monadic.xyz"
    if: |
      build.state == "failed" && build.branch == "master"
